# <div align="center"> <b>Experiment 1: Data Wrangling 1</b> </div>
### <div align="center"> <b>Name : Shravan Santosh Shidruk , PRN : 72311412K </b></div>
## <div align="center"> <b>Dataset Used : [Netflix Shows Dataset](https://www.kaggle.com/datasets/shivamb/netflix-shows) </b></div>
---
### <div align="center"> <b>Dataset Description </b></div>

The dataset used for this experiment is the “Netflix Movies and TV Shows Dataset” obtained from Kaggle.
It contains information about movies and TV shows available on Netflix such as title, director, cast, country, release year, rating, duration, and genre.

Source: https://www.kaggle.com/datasets/shivamb/netflix-shows

This dataset is useful for analyzing content distribution, trends in entertainment, and performing data preprocessing tasks due to the presence of missing values and mixed data types.

<b> Variable Descriptions: </b>
The dataset contains the following variables:

* show_id: Unique ID of the content
* type: Movie or TV Show (Categorical)
* title: Name of the content (Text)
* director: Director name (Categorical/Text)
* cast: Actors involved (Text)
* country: Country of origin (Categorical)
* date_added: Date added to Netflix (Date)
* release_year: Year of release (Numeric)
* rating: Content rating (Categorical)
* duration: Duration of content (Text)
* listed_in: Genre (Categorical)
* description: Summary of the content (Text)

---

### 1. Loading all important libraries

In [55]:
import pandas as pd
import numpy as np

### 2. Load the Dataset into Pandas DataFrame

In [56]:
df = pd.read_csv("netflix_titles.csv")

### 3. Data Preprocessing

In [57]:
# checking the shape of the dataset
print(f"The shape of the dataset is : {df.shape[0]} rows and {df.shape[1]} columns with total {df.shape[0] * df.shape[1]} records")

The shape of the dataset is : 8807 rows and 12 columns with total 105684 records

In [58]:
# printing all the column names
print(f"The names of the columns are : \n",list(df.columns))

The names of the columns are :
 ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

In [59]:
# total missing values in dataset
print(f"Total missing values in the Dataset : {df.isnull().sum().sum()}")
# missing values per column
print(f"Missing values per column in Dataset : \n{df.isnull().sum()}")

Total missing values in the Dataset : 4307
Missing values per column in Dataset :
show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [60]:
# checking the type of each column
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB
None

In [61]:
# we can also use this method to check data types
print(df.dtypes)

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [62]:
# printing Descriptive Statistics of numerical a column , here only release_year is numerical
print(df.describe())

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [63]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

### 4. Type Conversion

In [64]:
df["date_added"] = df["date_added"].str.strip()     # 1. removing extra spaces from dates
df["date_added"] = pd.to_datetime(df["date_added"]) # 2. converting date from obj to datetime data type
df["release_year"] = df["release_year"].astype(int) # 3. converting year into int

### 5. Data Normalization

In [65]:
import warnings
warnings.filterwarnings('ignore')


# Extract numeric duration
df['duration'] = df['duration'].astype(str).str.extract('(\d+)')

# Convert to numeric
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')

# Fill missing values
df['duration'] = df['duration'].fillna(df['duration'].mean())

# Normalize
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df[['duration', 'release_year']] = scaler.fit_transform(
    df[['duration', 'release_year']]
)

### 6. Converting Categorical to Numerical features

In [66]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['type'] = le.fit_transform(df['type'])
df['rating'] = le.fit_transform(df['rating'])
df['country'] = le.fit_transform(df['country'].astype(str))

In [67]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,NaN,603,2021-09-25,0.989583,7,0.286174,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,1,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",426,2021-09-24,1.000000,11,0.003215,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",748,2021-09-24,1.000000,11,0.000000,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,1,Jailbirds New Orleans,NaN,NaN,748,2021-09-24,1.000000,11,0.000000,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,1,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",251,2021-09-24,1.000000,11,0.003215,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...